export const projectData = [
  {
    id: 1,
    title: "HooBank",
    img: "images/HooBank.jpg",
    link: "https://aryakarthi.github.io/hoobank/",
    github: "https://github.com/aryakarthi/hoobank",
  },
  {
    id: 2,
    title: "Nike",
    img: "images/Nike.jpg",
    link: "https://aryakarthi.github.io/nike_clone/",
    github: "https://github.com/aryakarthi/nike_clone",
  },
  // {
  //   id: 3,
  //   title: "Madadz",
  //   img: "images/Madadz.avif",
  //   link: "",
  //   github: "",
  // },
  // {
  //   id: 4,
  //   title: "Madadz 2",
  //   img: "images/Madadz2.avif",
  //   link: "",
  //   github: "",
  // },
  {
    id: 5,
    title: "Piller",
    img: "images/Piller.avif",
    link: "https://piller-website.vercel.app/",
    github: "https://github.com/aryakarthi/Piller_Website",
  },
  {
    id: 6,
    title: "MiCare",
    img: "images/MiCare.avif",
    link: "https://micare-website.vercel.app/",
    github: "https://github.com/aryakarthi/Micare_Website",
  },
  // {
  //   id: 7,
  //   title: "Spin Drive",
  //   img: "images/SpinDrive.avif",
  //   link: "",
  //   github: "",
  // },
  // {
  //   id: 8,
  //   title: "Pinnacle",
  //   img: "images/Pinnacle.avif",
  //   link: "",
  //   github: "",
  // },
  {
    id: 9,
    title: "Virtual India",
    img: "images/VirtualIndia.avif",
    link: "https://www.virtualindia.co.in/",
    github: "",
  },
  {
    id: 10,
    title: "Restaurantly",
    img: "images/Restaurantly.jpg",
    link: "https://aryakarthi.github.io/restaurantly/",
    github: "https://github.com/aryakarthi/restaurantly",
  },
  {
    id: 11,
    title: "Adventours",
    img: "images/Adventours.jpg",
    link: "https://aryakarthi.github.io/adventours/",
    github: "https://github.com/aryakarthi/adventours",
  },
  {
    id: 12,
    title: "Presento",
    img: "images/Presento.jpg",
    link: "https://aryakarthi.github.io/presento/",
    github: "https://github.com/aryakarthi/presento",
  },
  {
    id: 13,
    title: "Flexor",
    img: "images/Flexor.jpg",
    link: "https://aryakarthi.github.io/flexor/",
    github: "https://github.com/aryakarthi/flexor",
  },
  {
    id: 14,
    title: "AnimeVault",
    img: "images/AnimeVault.jpg",
    link: "https://anime-vault-blue.vercel.app/",
    github: "https://github.com/aryakarthi/anime_vault",
  },
  {
    id: 15,
    title: "ImgSlider",
    img: "images/ImgSlider.jpg",
    link: "https://aryakarthi.github.io/img_slider/",
    github: "https://github.com/aryakarthi/img_slider",
  },
  {
    id: 16,
    title: "WeatherFlix",
    img: "images/WeatherFlix.jpg",
    link: "https://weather-flix.vercel.app/",
    github: "https://github.com/aryakarthi/weather_flix",
  },
  // {
  //     id: 17,
  //     title: "Todos",
  //     img: "images/Todos.jpg",
  //     link: "https://aryakarthi.github.io/todoApp/",
  //     github: "https://github.com/aryakarthi/todoApp",
  // },
];
